name: move issue
on:
  issues:
    types:
      - assigned

# map fields with customized labels
env:
  todo: Todo
  done: Done
  in_progress: In Progress

jobs:
  move_issue:
    name: issue_assigned
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'assigned')
    steps:
      - name: Move issue to ${{ env.in_progress }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.ACCESS_TOKEN }}
          user: alabeli
          # organization: sample-org
          project_id: 2
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.in_progress }} # Target status
