# This is a basic workflow to help you get started with Actions

name: manage-issue-move
on:
  issues:
    types: [assigned]
jobs:
  move_issue:
        runs-on: ubuntu-latest
        steps:
        - name: auto-move-related-issue
      # You may pin to the exact commit or the version.
      # uses: 1natsu172/github-action-auto-move-related-issue@25117b43182a8d55ae82fcfdf6d9f80202e6f660
          uses: 1natsu172/github-action-auto-move-related-issue@v1
          with:
        # Secret GitHub API token to use for API requests.
            github_token: ${{ github.token }}
      # This Action's config.
            config: auto-move-related-issue-config.yml
